### PR TITLE
Add converter from swagger_2 to openapi_3

### PR DESCRIPTION
**Pull request by MikeRalphson**
Refs #112 

First pass for comments. Conversion from swagger_2 to openapi_3 format. Automatic conversions of other formats through swagger_2 has not been implemented (i,e. it is currently a manual two-stage process).

Doesn't support the recently added `--order` option.

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Sorry, just saw the "first pass for comments" line. Hopefully the merge/revert didn't screw up the commit history too much - not sure if there's a way to re-open this PR

**Comment by bobby-brennan** [comment]
Erased the merge/revert from commit history, so you should be able to re-open the PR without a rebase.

**Comment by MikeRalphson** [comment]
Well, it of course it's ok to merge if there are no comments :smile: but seriously, please let me know if there are any problems with the approach or implementation...

**Comment by bobby-brennan** [comment]
Looks good to me :) re-merged in #129 and published as 2.5.0

**Pull request merged**
