### PR TITLE
issue #172: include OpenAPI 3.0.1 element for --order openapi

### LINKED ISSUE #172: --order openapi should include `openapi` and `servers`
For openapi_3 output, the `openapi` order should include `openapi` at the top of the list, and `servers` after `info`, etc. as per https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#openapi-object , so that converting `--to=openapi_3` puts those values in the expected place.

### PR DESCRIPTION
**Pull request by DavidBiesack**
add `'components'`, `'servers'`, and `'openapi'` so `--order openapi` works with `--to openapi_3`; fixes #172 

Note: I could not get the build to run cleanly to to native fsevents when I tried `npm install`. Hence, I could also not test with `WRITE_GOLDEN=true npm test` even at master in a clean repo without my changes. but other manual tests worked OK with this changes.

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Thanks! You can revert the version change, and I'll bump when I push the release.

**Comment by bobby-brennan** [comment]
Actually, it looks like node v6 doesn't like the fsevents dependency. What version of node are you using?

**Comment by DavidBiesack** [comment]
I reverted the version back.
I'm using: 
```
$ npm --version
5.6.0
$ node --version
v8.11.3
```
On a different MacBook, this built OK and tests ran ok:
```

SUMMARY:
✔ 35 tests completed
```

**Comment by DavidBiesack** [comment]
I'm going to close this since too much time has passed and code has diverged; too difficult to resolve conflicts. Will submit a clean PR

**Pull request closed without merging**
