### PR TITLE
Alternative Swagger Fields Ordering

### PR DESCRIPTION
**Pull request by adrolet**
This request adds the possibility to sort fields differently.

The current sorting, put fields like 'swagger' at the end of the file.

Looking at some examples on the web and our local practices
I realized that many prefer to have fields like : 
  swagger, info, basePath, schemes
around the top of the file.

These are then followed by paths, and definitions.

I tried to find some authoritative sources for a formal order.
The best I came with (that align with my preferences) is a list of fields 
on the swagger (OpenApi) page at:
https://swagger.io/specification/#swagger-object-14

This request provides an option to oder fields as the appear on that page.

The default alphabetical order is preserved if no -o or --order flag is provided.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
👍 for the feature.  Just for reference, here's the implementation used by the APIs.guru [management scripts](https://github.com/APIs-guru/openapi-directory/blob/master/scripts/util.js#L59).

**Comment by bobby-brennan** [comment]
Looks good!

I think Mike's point about using an array makes sense. Usually when sorting like this I put the array in reverse order, so the "not found" index of -1 puts missing elements at the end of the ordering.

```js
let order = [
  'three',
  'two',
  'one',
];

['four', 'one', 'three'].sort((n1, n2) => {
  let i1 = order.indexOf(n1);
  let i2 = order.indexOf(n2);
  if (i1 === i2) return 0;
  return i1 < i2 ? 1 : -1;
})

// ['one', 'three', 'four']
```

One other nit: let's use "openapi" and "alphabetical" instead of "oa" and "az".

Also, I don't see any reason not to default to "openapi" ordering.  It should be fully backward compatible - we only sorted alphabetically to keep the test output from thrashing.

**Comment by adrolet** [comment]
Hi Guys

Thank you for the feedback.
As I previously indicated I'm new to JS, 
I can do code that works, but you are helping me in doing better JS code.

I'm coding this mostly night time.
I'll convert the code to use the array.
It may take me a few days, given other activities I have, but it will come.

I'll also use the long form for the flags.
I assumed most people would be happy to type less (and have less typos, like I do!).
Long form is definitively more meaningful however.

I'll try to make alphabetical the default,
but I'm also trying to not re-issue all output files.
I'll probably just pass an extra arg to the test suite.
Give me time to look again at this code.

---
On a personal note, Bobby is the picture you use a Corgi?
We are just about to bring one home this weekend.

**Comment by adrolet** [comment]
Array coded, 
but I have issues with the new order values.

If I use a syntax like
`  --from=swagger_1 --to=swagger_2 --order=alphabetical`
it works.

If I use the short for -o
`  --from=swagger_1 --to=swagger_2 -o=alphabetical`
The "t" in alphabetical, gets confused with the -t short form option
and options.to becomes "-i"

My understanding is that none of the short form flag can appear as a char 
in one of the option values.
Is this right? Are you aware of how to go around this?

Else, what about simply using for order: "openapi" and "alpha".
That should work.

**Comment by bobby-brennan** [comment]
That's strange, maybe some issue with commander.js.  I'm good with just using openapi/alpha.

(and my dog is a shiba inu and terrirer mix, we think - not really sure since she was adopted. Congrats on becoming a new dog owner!)

**Comment by adrolet** [comment]
The requested changes are in.
I hope all is OK.

If Bobby thinks it is a good idea, the api.guru order could be added as a 3rd order value.
It looks close to openapi, but has a few differences, and has more values.

Mike is it something you would like to do?
If not I could consider this for a new feature a bit later.

**Comment by MikeRalphson** [comment]
Hi @adrolet yes, I think this is something we could look at adding later, it doesn't need to hold up this PR. The APIs.guru scripts do the sorting right at the end, after some patching so I'm not sure I could just take that out and rely on api-spec-converter's sorting (though as I said, I think it's an excellent improvement).

**Comment by bobby-brennan** [comment]
Looks good, thanks for the contribution!

**Comment by bobby-brennan** [comment]
Published as 2.4.0

**Pull request merged**
