### PR TITLE
Yaml output

### PR DESCRIPTION
**Pull request by adrolet**
Added a command line option, and argument to spec.stringify, 
to allow spec output to be json or yaml formatted.

I would have called this option "format" but since this word is already heavily
used in this library to indicate the  different types of specification supported,
I used the word "syntax" to refer to the json and yaml format.
I'm open to suggestion if you have a better term!

I have added 2 test cases to validate the actual output.
The current test suites only focused on testing the conversion.

I'm new to JavaScript, so I hope the way I modified the code is reasonable!

### CODE REVIEW

**Comment by adrolet** [comment]
Will try to submit again tomorrow to fix the travis run.
Strangely this error did not show up in all other local tests I did.
Well, I'm still in the learning stage of JS.

looks like it's a minor thing to fix.

**Comment by bobby-brennan** [comment]
Looks good!  The issue with Travis is that we're still targeting Node 4.x, which doesn't support default parameter values. So

```js
function(syntax = 'json') {
  // ...
}
```

should become

```js
function(syntax) {
  syntax = syntax || 'json';
  // ...
}
```

Once that's fixed, looks good to merge.  Thanks for contributing!

**Comment by adrolet** [comment]
Thx for the explanation. 
That what I also got by quickly searching the web at breakfast time this morning.
I'll try to do the update this evening one back at home.

I'm glad you like it! :-)

**Comment by bobby-brennan** [comment]
Thanks!

**Comment by bobby-brennan** [comment]
Published as 2.3.0

**Comment by adrolet** [comment]
Thank you.
I have another small output enhancement coming.
Most likely this week.

**Pull request merged**
