### PR TITLE
Add vendor specific JSON types support for OAPI3 -> Swagger2 conversion

### PR DESCRIPTION
**Pull request by MrGuiMan**
- Update tests to handle vendor json mime types 
- Test json mime types with a regex to allow vendor types

### CODE REVIEW

**Comment by MrGuiMan** [comment]
@bobby-brennan Travis did not like me using Object.values, do you reckon I should replace it by a getter property inside SUPPORTED_MIME_TYPES ?

**Comment by bobby-brennan** [comment]
We're still targeting Node v6, which seems not to support Object.values. You could use Object.keys or pre-compute an array of values - up to you on how to solve.

**Comment by bobby-brennan** [comment]
Thanks for the contribution!

**Comment by bobby-brennan** [comment]
Published as 2.7.0

**Pull request merged**
