### PR TITLE
add transitive conversion to Open API 3.0 via Swagger 2.0

### PR DESCRIPTION
**Pull request by bobby-brennan**
@MikeRalphson FYI - pretty simple change, but lmk if you have concerns/suggestions. Otherwise I'll merge tomorrow.

Once this is in, I'll update the web demo (https://github.com/LucyBot-Inc/api-spec-converter/pull/138)

### CODE REVIEW

**Comment by MikeRalphson** [comment]
LGTM! Very neat and it's nice to have an extensible pipeline. I've just released v2.10.0 of swagger2openapi, it'd be great if you could update the dependency and check there's no errors - whether any changes to the test output look ok.

**Comment by MikeRalphson** [comment]
apib2swagger has also recently released v1.0.0

**Comment by bobby-brennan** [comment]
Managed to update apib2swagger, but I'm having trouble with swagger2openapi@2.10.0. It seems there's some syntax in reftools that's tripping up browserify...I tried webpack as well but hit the same issue. Did you update reftools in the latest release?

**Comment by MikeRalphson** [comment]
Yes, 2.10.0 is the first to use reftools. Any idea what is upsetting browserify? I think webpack 3 runs OK over it, but with check.

**Comment by MikeRalphson** [comment]
Don't let it hold up your PR if you want to pin to 2.9.x for now.

**Comment by MikeRalphson** [comment]
* https://wzrd.in/bundle/reftools@0.0.3 bundles ok
* https://wzrd.in/bundle/reftools@0.0.4 doesn't

Will have a look at the diff.

**Comment by MikeRalphson** [comment]
Ok swagger2openapi v2.10.1 uses reftools 0.0.10 which bundles ok using wzrd.in - the problem appears to have been the `main` in `package.json` pointing to a non-existent file. Can you retry with this version?

**Comment by bobby-brennan** [comment]
Unfortunately still hitting the same problem. For some reason babel isn't replacing `let` with `var` and it's getting tripped up on these lines:

```js
function shallowClone(obj) {
    let result = {};
    for (let p in obj) {
        if (obj.hasOwnProperty(p)) {
            result[p] = obj[p];
        }
    }
    return result;
}
```

It must be something wrong with the babel configuration. I'm going to merge this in with swagger2openapi@2.9.0, but will try and mess with babel once that's done.

**Pull request merged**
